In [1]:
import numpy as np
import torch
import qtorch
from qtorch.quant import bfloat16_posit8_quantize

Using /home/himeshi/.cache/torch_extensions/py310_cu126 as PyTorch extensions root...
Emitting ninja build file /home/himeshi/.cache/torch_extensions/py310_cu126/quant_cpu/build.ninja...
Building extension module quant_cpu...
Allowing ninja to set a default number of workers... (overridable by setting the environment variable MAX_JOBS=N)


ninja: no work to do.


Loading extension module quant_cpu...
Using /home/himeshi/.cache/torch_extensions/py310_cu126 as PyTorch extensions root...
Detected CUDA files, patching ldflags
Emitting ninja build file /home/himeshi/.cache/torch_extensions/py310_cu126/quant_cuda/build.ninja...
/home/himeshi/conga25/conga25env/lib/python3.10/site-packages/torch/utils/cpp_extension.py:2356: UserWarning: TORCH_CUDA_ARCH_LIST is not set, all archs for visible cards are included for compilation. 
If this is not desired, please set os.environ['TORCH_CUDA_ARCH_LIST'].
  warnings.warn(
Building extension module quant_cuda...
Allowing ninja to set a default number of workers... (overridable by setting the environment variable MAX_JOBS=N)


[1/3] c++ -MMD -MF quant_cuda.o.d -DTORCH_EXTENSION_NAME=quant_cuda -DTORCH_API_INCLUDE_EXTENSION_H -DPYBIND11_COMPILER_TYPE=\"_gcc\" -DPYBIND11_STDLIB=\"_libstdcpp\" -DPYBIND11_BUILD_ABI=\"_cxxabi1016\" -isystem /home/himeshi/conga25/conga25env/lib/python3.10/site-packages/torch/include -isystem /home/himeshi/conga25/conga25env/lib/python3.10/site-packages/torch/include/torch/csrc/api/include -isystem /usr/local/cuda/include -isystem /home/himeshi/.pyenv/versions/3.10.4/include/python3.10 -D_GLIBCXX_USE_CXX11_ABI=1 -fPIC -std=c++17 -O3 -std=c++17 -fPIC -c /home/himeshi/conga25/QPyTorch/qtorch/quant/quant_cuda/quant_cuda.cpp -o quant_cuda.o 
[2/3] /usr/local/cuda/bin/nvcc --generate-dependencies-with-compile --dependency-output quant.cuda.o.d -DTORCH_EXTENSION_NAME=quant_cuda -DTORCH_API_INCLUDE_EXTENSION_H -DPYBIND11_COMPILER_TYPE=\"_gcc\" -DPYBIND11_STDLIB=\"_libstdcpp\" -DPYBIND11_BUILD_ABI=\"_cxxabi1016\" -isystem /home/himeshi/conga25/conga25env/lib/python3.10/site-packages/torch/

Loading extension module quant_cuda...


In [2]:
a = np.arange(-20,20,2.5)
a = torch.tensor(a, dtype=torch.bfloat16)
print (a)

tensor([-20.0000, -17.5000, -15.0000, -12.5000, -10.0000,  -7.5000,  -5.0000,
         -2.5000,   0.0000,   2.5000,   5.0000,   7.5000,  10.0000,  12.5000,
         15.0000,  17.5000], dtype=torch.bfloat16)


In [3]:
p = bfloat16_posit8_quantize(a,nsize=8,es=1)
print(p.dtype)
print(p)

torch.bfloat16
tensor([-20.0000, -16.0000, -15.0000, -12.0000, -10.0000,  -7.5000,  -5.0000,
         -2.5000,   0.0000,   2.5000,   5.0000,   7.5000,  10.0000,  12.0000,
         15.0000,  16.0000], dtype=torch.bfloat16)


In [4]:
p2= bfloat16_posit8_quantize(a,nsize=7,es=1)
print(p2.dtype)
print(p2)

torch.bfloat16
tensor([-16.0000, -16.0000, -16.0000,  -8.0000,  -6.0000,  -4.0000,  -6.0000,
         -1.5000,   0.0000,   1.5000,   6.0000,   4.0000,   6.0000,   8.0000,
         16.0000,  16.0000], dtype=torch.bfloat16)


In [5]:
p3 = bfloat16_posit8_quantize(a,nsize=6,es=1)
print(p3.dtype)
print(p3)

torch.bfloat16
tensor([-16., -16., -16.,  -4.,  -4.,  -4.,  -4.,  -2.,   0.,   2.,   4.,   4.,
          4.,   4.,  16.,  16.], dtype=torch.bfloat16)
