In [2]:
import numpy as np
import torch
import qtorch
from qtorch.quant import bfloat16_posit8_quantize

Using /home/himeshi/.cache/torch_extensions/py310_cu126 as PyTorch extensions root...
Emitting ninja build file /home/himeshi/.cache/torch_extensions/py310_cu126/quant_cpu/build.ninja...
Building extension module quant_cpu...
Allowing ninja to set a default number of workers... (overridable by setting the environment variable MAX_JOBS=N)


ninja: no work to do.


Loading extension module quant_cpu...
Using /home/himeshi/.cache/torch_extensions/py310_cu126 as PyTorch extensions root...
Detected CUDA files, patching ldflags
Emitting ninja build file /home/himeshi/.cache/torch_extensions/py310_cu126/quant_cuda/build.ninja...
/home/himeshi/conga25/conga25env/lib/python3.10/site-packages/torch/utils/cpp_extension.py:2356: UserWarning: TORCH_CUDA_ARCH_LIST is not set, all archs for visible cards are included for compilation. 
If this is not desired, please set os.environ['TORCH_CUDA_ARCH_LIST'].
  warnings.warn(
Building extension module quant_cuda...
Allowing ninja to set a default number of workers... (overridable by setting the environment variable MAX_JOBS=N)


ninja: no work to do.


Loading extension module quant_cuda...


In [3]:
a = np.arange(-20,20,2.5)
a = torch.tensor(a, dtype=torch.float)
print (a)

b = a.to(torch.bfloat16)
print (b)


tensor([-20.0000, -17.5000, -15.0000, -12.5000, -10.0000,  -7.5000,  -5.0000,
         -2.5000,   0.0000,   2.5000,   5.0000,   7.5000,  10.0000,  12.5000,
         15.0000,  17.5000])
tensor([-20.0000, -17.5000, -15.0000, -12.5000, -10.0000,  -7.5000,  -5.0000,
         -2.5000,   0.0000,   2.5000,   5.0000,   7.5000,  10.0000,  12.5000,
         15.0000,  17.5000], dtype=torch.bfloat16)


In [4]:
c = bfloat16_posit8_quantize(b,nsize=8,es=1)
print(c)

tensor([-20.0000, -16.0000, -15.0000, -12.0000, -10.0000,  -7.5000,  -5.0000,
         -2.5000,   0.0000,   2.5000,   5.0000,   7.5000,  10.0000,  12.0000,
         15.0000,  16.0000], dtype=torch.bfloat16)


In [5]:
d = bfloat16_posit8_quantize(b,nsize=7,es=2)
print(d)

tensor([-16.0000, -16.0000, -16.0000,  -8.0000,  -6.0000,  -4.0000,  -1.5000,
         -6.0000,   0.0000,   6.0000,   1.5000,   4.0000,   6.0000,   8.0000,
         16.0000,  16.0000], dtype=torch.bfloat16)


In [10]:
e = bfloat16_posit8_quantize(b,nsize=6,es=2)
print(e)

tensor([-16., -16., -16.,  -4.,  -1.,  -1.,  -1.,  -1.,   0.,   1.,   1.,   1.,
          1.,   4.,  16.,  16.], dtype=torch.bfloat16)


Test GPU functions.

In [7]:
# Get the GPU device
device = torch.device("cuda:0")

# Copy the tensor to the GPU device
a_gpu = a.to(device)
print(a_gpu)

b_gpu = a_gpu.to(torch.bfloat16)
print(b_gpu)

tensor([-20.0000, -17.5000, -15.0000, -12.5000, -10.0000,  -7.5000,  -5.0000,
         -2.5000,   0.0000,   2.5000,   5.0000,   7.5000,  10.0000,  12.5000,
         15.0000,  17.5000], device='cuda:0')
tensor([-20.0000, -17.5000, -15.0000, -12.5000, -10.0000,  -7.5000,  -5.0000,
         -2.5000,   0.0000,   2.5000,   5.0000,   7.5000,  10.0000,  12.5000,
         15.0000,  17.5000], device='cuda:0', dtype=torch.bfloat16)


In [8]:
c_gpu = bfloat16_posit8_quantize(b_gpu,nsize=8,es=1)
print(c_gpu)

tensor([-20.0000, -16.0000, -15.0000, -12.0000, -10.0000,  -7.5000,  -5.0000,
         -2.5000,   0.0000,   2.5000,   5.0000,   7.5000,  10.0000,  12.0000,
         15.0000,  16.0000], device='cuda:0', dtype=torch.bfloat16)


In [9]:
d_gpu = bfloat16_posit8_quantize(b_gpu,nsize=7,es=1)
print(d_gpu)

tensor([-16.0000, -16.0000, -16.0000,  -8.0000,  -6.0000,  -4.0000,  -6.0000,
         -1.5000,   0.0000,   1.5000,   6.0000,   4.0000,   6.0000,   8.0000,
         16.0000,  16.0000], device='cuda:0', dtype=torch.bfloat16)


In [11]:
e_gpu = bfloat16_posit8_quantize(b_gpu,nsize=6,es=2)
print(e_gpu)

tensor([-16., -16., -16.,  -4.,  -1.,  -1.,  -1.,  -1.,   0.,   1.,   1.,   1.,
          1.,   4.,  16.,  16.], device='cuda:0', dtype=torch.bfloat16)
